### ISSUE TITLE
The wrong number of displayed spaces when multibyte string is given

### ISSUE THREAD

**Issue by ubnt-intrepid** [mgattozzi/ferris-says#2]
## Expected output
```
--------------------
| 突然の死👻      |
--------------------
              \
               \
                  _~^~^~_
              \) /  o o  \ (/
                '_   -   _'
                / '-----' \
```
## Actual output
```
--------------------
| 突然の死👻 |
--------------------
              \
               \
                  _~^~^~_
              \) /  o o  \ (/
                '_   -   _'
                / '-----' \
```

## Step to reproduce
```console
$ echo "突然の死👻" | fsays --width 16
```

## Additional information
* PHP provides a function [`mb_strwidth()`](http://php.net/manual/en/function.mb-strwidth.php), which calculates the width of multibyte strings.  In this function, the width of an unicode character is assumed as follows:

    | chars | width |
    |:-|:-|
    | U+0000 - U+0019 | 0 |
    | U+0020 - U+1FFF  | 1 |
    | U+2000 - U+FF60 | 2 |
    | U+FF61 - U+FF9F | 1 |
    | U+FFA0 -  | 2 |

**Comment by mgattozzi** [comment]
I did the American thing of accounting for ASCII and not Unicode when doing this. Thanks for opening it up! I think the solution would be something like [this](http://brandonio21.com/2016/04/rust-you-probably-meant-to-use-chars-count/) and iterating over characters of a string rather than counting bytes in a string to solve the problem. I don't think I'll be able to get to this soon but I'm happy to take a PR. Thanks for the detailed bug report :D

**Comment by ubnt-intrepid** [comment]
I'll try to create the patch and send the PR. Please wait a moment...

**Comment by mgattozzi** [comment]
No rush @ubnt-intrepid! I'm looking forward to it when you can get it done and once it's in I'll push a new version with the fix :D

**Comment by dynnamitt** [comment]
Cant yout swap input param to &str (and use OsStr internally )
https://hermanradtke.com/2015/05/03/string-vs-str-in-rust-functions.html
