### ISSUE TITLE
No output and program stuck when calling `fsays` without arguments

### ISSUE THREAD

**Issue by robamu** [mgattozzi/ferris-says#24]
Hello,

Maybe I am using the binary in a wrong way..
If I call it without any arguments, nothing happens and it appears to be stuck.

I've looked a bit at the code because I was interested and the program appears to be stuck in the following section
at line 106 of main.rs

```rust
  let reader = BufReader::new(stdin.lock()).bytes().fold(
      Ok(Vec::new()),
      |a: Result<Vec<u8>>, b| {
          if let Ok(mut a) = a {
              a.push(b.chain_err(|| INPUT)?);
              Ok(a)
          } else {
              a
          }
      },
  )?;
 ```

I'm nowhere nearly experienced yet to know hat is happening here. I've printed `a` in the closure and it appears to fill some vector with everything I type, but it does not react to something like a newline. Do you have any idea what might cause this?

Also, is there a way to build the binary from the root of the crate in some way? I need to navigate into `fsays` to run `cargo run` , which builds the project binary in the root, but I can' t run `cargo build --bin fsays` from the root

**Comment by mgattozzi** [comment]
Hey @robamu maybe you know what I'm about to type, maybe you don't. This is more just some information about unix in general and why the binary is working correctly and probably just you using it incorrectly. Maybe you're not though so correct me if I'm wrong here!

In unix we have 3 specific files that every process uses `stdin`, `stdout`, and `stderr`. The last two are just your outputs in a terminal that are in rust `println/eprintln` respectively. They are just files at the end of the day that get data input to them. With `stdin` it's kind of the same. It's a "file" that can be printed to for the program to read from. You see this in commands where you'd use pipes in unix systems like so:

```bash
❯ echo "foo\nbar\nbar\nfoo" | sort
bar
bar
foo
foo
```

The `echo` command writes the data into the `stdin` of the `sort` program. Which is exactly is what happens here with `fsays`:

```bash
❯ echo "This is a test" | cargo run -p fsays
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/fsays`
 ________________
< This is a test >
 ----------------
        \
         \
            _~^~^~_
        \) /  o o  \ (/
          '_   -   _'
          / '-----' \
```

So why does the above work and not what you did? I suspect it's because you're not actually sending an `EOF` (end of file) character over stdin:

```bash
❯ cargo run -p fsays
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/fsays`
testing one two three
 _______________________
< testing one two three >
 -----------------------
        \
         \
            _~^~^~_
        \) /  o o  \ (/
          '_   -   _'
          / '-----' \
```

This is `ctrl-d` on unix of `ctrl-z` on windows. So what's happening here is that your program is taking input, but is waiting for all of it to be done before printing out. It would be bad if it printed out before it had everything! When you pipe a command into another in unix this will send the `EOF` to tell the program to close the handle to `stdin`. So our `stdin` reader here is thinking "There's still more data so just keep reading until I get the signal otherwise". The program is working as is expected, but if you're unfamiliar with how unix systems or cli tools work with stdin in general it's really confusing and weird. Frankly I wish we had a better interface for command line programs rather than something cooked up in Bell Labs in the 70s but here we are 🤷🏻‍♂️

Hopefully this answers your question! If not let me know and I can expand more on it here. I'll keep the issue open until you're satisfied with an answer and understand what's going on. 😄 

If you want to run the binary you'll need to use `cargo build --package fsays` or the shorthand `cargo build -p fsays` since the binary is part of the workspace and not an individual bin file. You can find the relevant documentation on [workspaces here](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html). The reason this is the case is due to https://github.com/mgattozzi/ferris-says/issues/19 which also links the relevant commits that changed this behavior if you're curious as using `cargo build --bin fsays` was the original behavior.

**Comment by robamu** [comment]
Thanks for the excellent explanation, definitely learned a few things, and `cowsay` actually behaves exactly the same :+1: 

You can close this.
