### ISSUE TITLE
Add the cow from cowsay

### ISSUE THREAD

**Issue by robamu** [mgattozzi/ferris-says#25]
I think it would be nice if one could invoke `fsays` to display the cow as well. The original cowsay is also able to display different animals. What do you think about this feature? I might look into this, as a practical project to learn Rust as well. 

The original `cowsay` also supported other animals: https://github.com/tnalpgge/rank-amateur-cowsay/tree/master/cows

**Comment by mgattozzi** [comment]
My reasoning for closing this issue is similar to [this comment on another PR](https://github.com/mgattozzi/ferris-says/pull/22#issuecomment-865191151). It's a Rust focused project with high visibility externally. I think just ferris and clippy being here are fine for the project. However, if you want to fork this and use it as a way to practice Rust I 100% believe it would be a great way to learn! The code base here is quite small so modifying it to do what you want would be a great introduction to using Rust with some easily visual feedback on if it is working or not. I will not accept this as an upstream feature however. I do appreciate the fact that you opened up an issue before implementing a whole PR only to have it rejected as it's not something I like doing especially given time was spent on it!
